[package]
name = "asmkit-x86_64"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asmkit-core = { path = "../asmkit-core", version = "0.0.0" }